### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by d-cameron** [ma-compbio/Weaver#12]
The definition of otemp_1 in LBP.cpp is commented out thus causing a compilation error:

```
g++ -std=c++0x -O3 -fopenmp -I. -I../inc -I /home/yangli9/tools/boost_1_55_0/  -c LBP.cpp -o LBP.o
LBP.cpp: In function âvoid Viterbi_new(std::map<std::basic_string<char>, std::vector<site> >&, std::map<std::basic_string<char>, std::map<interval, region_numbers> >&, std::map<std::basic_string<char>, std::map<int, std::basic_string<char> > >&, std::map<std::basic_string<char>, std::map<int, double> >&, std::vector<observe>&, std::set<site>&, std::set<site>&, std::set<site>&, std::set<site>&, std::map<std::basic_string<char>, std::map<int, int> >&, std::vector<int>&, std::map<CA, int>&, int, std::map<std::basic_string<char>, std::map<int, CA> >&, std::map<CA, CA>&, std::vector<std::basic_string<char> >&)â:
LBP.cpp:2543:6: error: âotemp_1â was not declared in this scope
      otemp_1 << chr << "\t" << JOB_LIST[chr][i].begin << "\t" << JOB_LIST[chr][i].end << "\t" << JOB_LIST[chr][i].type << "\t" << JOB_LIST[chr][i].final_state.Major << "\t" << JOB_LIST[chr][i].mm << "\t" << JOB_LIST[chr][i].final_state.Major_base << endl;
      ^
make: *** [LBP.o] Error 1
```

**Comment by ma-compbio** [comment]
Thank you for your questions. We are in the process of checking these and improve the documentation/script. We will let you know as soon as possible.

**Comment by advorkin** [comment]
Hello,

We are experiencing the same problem.  Please let us know if there is an update.

Thank you.

**Comment by ashokrajaraman** [comment]
Hi d-cameron, advorkin. 

We changed the installation procedure to use Cmake. The latest version on the Master branch should take care of this, as well as detailed instructions to install and use Weaver. This also takes care of the error you had in compiling Weaver.

**Comment by advorkin** [comment]
Thank you!  I was able to successfully compile Weaver.  I really appreciate your quick response.

have a wonderful day,
Asya

----- Original Message -----
