### ISSUE TITLE
Documentation does not match source code

### ISSUE THREAD

**Issue by d-cameron** [ma-compbio/Weaver#14]
I am attempting to run weaver and, for the programs I have attempted to run, neither the online github documentation, nor the program usage help match the actual command-line arguments required. To run these programs, I have had to look and the source code for the relevant .pl to work out how to run it.

For example:
* Weaver_SV.pl
  * github documentation lists only a BAM as the required input. When running the program, it indicates that the reference fasta is also required.
* Weaver_pipeline.pl
  * the first two arguments loaded into the `$RUN_TYPE` and `$MODEFLAG` variables are not mentioned anywhere in the documentation.
  * --gap documentation appears to be for --fa
  * multiple arguments not marked as [MANDATORY] are mandatory
  * Setting -F still requires --fa as the check for an empty `$FA` occurs before `$FULLFA` is set. Is this parameter intended to allow for the bwa & bowtie indexes to not require colocation with the reference fasta?

Does there exist an all-in-one wrapper that can go from bam to weaver output for hg19 and/or hg38?

**Comment by ashokrajaraman** [comment]
README rewritten extensively to aid running Weaver. Sub-commands abstracted out.
